---
stages:
- name: SelfAssembly
  inputs:
  - type: git
    branch: master
  triggers:
  - type: commit
  jobs:
  - name: WrapPresent
    type: builder
    artifact_dir: ./
    build_type: shell
    script: |-
      #!/bin/bash
      # © Copyright IBM Corporation 2015.
      #
      # All rights reserved. This program and the accompanying materials
      # are made available under the terms of the Eclipse Public License v1.0
      # which accompanies this distribution, and is available at
      # http://www.eclipse.org/legal/epl-v10.html
      # Derived from dW article @ https://developer.ibm.com/bluemix/2014/02/17/deploy-drupal-application-ibm-bluemix/
      ##########
      # Colors - Lets have some fun ##
      ##########
      Green='\e[0;32m'
      Red='\e[0;31m'
      Yellow='\e[0;33m'
      Cyan='\e[0;36m'
      no_color='\e[0m' # No Color
      beer='\xF0\x9f\x8d\xba'
      delivery='\xF0\x9F\x9A\x9A'
      beers='\xF0\x9F\x8D\xBB'
      eyes='\xF0\x9F\x91\x80'
      cloud='\xE2\x98\x81'
      litter='\xF0\x9F\x9A\xAE'
      fail='\xE2\x9B\x94'
      harpoons='\xE2\x87\x8C'
      tools='\xE2\x9A\x92'
      present='\xF0\x9F\x8E\x81'
      #############
      echo ""
      echo -e "${cloud}${Cyan}  Let's setup Drupal for initial deployment${no_color}"
      echo -e "${tools}${Yellow}    Updating apt-get ...${no_color}"
      sudo apt-get update > /dev/null 2>&1
      # Install jq
      echo -e "${tools}${Yellow}    Installing jq for JSON parsing support...${no_color}"
      sudo apt-get --assume-yes install jq > /dev/null 2>&1
      echo -e "${tools}${Yellow}    Installing zip/unzip...${no_color}"
      sudo apt-get --assume-yes install zip unzip > /dev/null 2>&1
      
      # Let's pull the open source code for Twilio-php SDK
      echo -e "${harpoons}${Yellow}    Updating git submodules ...${no_color}"
      git submodule update --init --recursive > /dev/null 2>&1
      
      echo -e "${harpoons}${Yellow}    Fetching Drupal Zip ...${no_color}"
      mkdir htdocs
      wget http://ftp.drupal.org/files/projects/drupal-7.41.zip -nv -O ./bluezone/drupal.zip
      echo -e "${tools}${Yellow}    Extracting Drupal${no_color}"
      unzip -o ./bluezone/drupal.zip -d ./htdocs > /dev/null 2>&1
      
      echo -e "${tools}${Cyan}    Setting up user provided modules ...${no_color}"
      for f in ./bluezone/configtweaks/plugins; do
          if [ -d ${f} ]; then
              # Will not run if no directories are available
              echo -e "${harpoons}${Cyan}      Installing ${f} User-Provided Module ...${no_color}"
              # mv $f ./htdocs/drupal/plugins
          else
              echo -e "${fail}${Cyan}      No User-Provided Modules detected...${no_color}"
          fi
      done
      
      # Organize the artifact structure to be CF PHP Buildpack friendly
      echo -e "${cloud}${Yellow}    Making artifacts CF PHP friendly ...${no_color}"
      mv ./bluezone/configtweaks/.bp-config .
      mkdir .extensions
      mv ./bluezone/configtweaks/.php-extensions .
      
      # Organize the artifact structure to facilitate BMX deploy
      echo -e "${cloud}${Yellow}    Making drupal artifacts ${Cyan}Bluemix ${Yellow}friendly ...${no_color}"
      mv ./bluezone/configtweaks/.user.ini ./htdocs/drupal-7.41
      # mv ./bluezone/configtweaks/.htaccess ./htdocs/drupal-7.41
      #
      # Embed config file if provided
      if [ -f "./bluezone/configtweaks/settings.php" ]; then
         echo -e "${tools}${Cyan}    Drupal Config file detected ...${no_color}"
         mv ./bluezone/configtweaks/settings.php ./htdocs/drupal-7.41/sites/default
      else
         echo -e "${tools}${Cyan}    NO Drupal Config file detected, using default ...${no_color}"
         cp ./htdocs/drupal-7.41/sites/default/default.settings.php ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "$services = getenv(\"VCAP_SERVICES\");" >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "$services_json = json_decode($services,true);" >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "if (isset($services_json)) {" >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "  if (isset($services_json[\"user-provided\"][0][\"credentials\"])) {" >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "    $postgres_config = $services_json[\"user-provided\"][0][\"credentials\"];" >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "    list($hostname, $port) = explode(':', $postgres_config[\"public_hostname\"]);"
         echo -e "    $dbname = 'compose'"
         echo -e "  }" >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "}" >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "$databases = array (" >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "  'default' =>" >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "  array (" >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "    'default' =>" >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "    array (" >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "      'driver' => 'pgsql'," >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "      'database' => $dbname," >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "      'username' => $postgres_config[\"username\"]," >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "      'password' => $postgres_config[\"password\"]," >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "      'host' => $hostname," >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "      'port' => $port," >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "      'prefix' => 'main_'" >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "    )," >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e "  )," >> ./htdocs/drupal-7.41/sites/default/settings.php
         echo -e ");" >> ./htdocs/drupal-7.41/sites/default/settings.php
      fi
      
      # Cleaning up
      echo -e "${litter}${Yellow}    Cleaning up repository...${no_color}"
      rm -rf ./bluezone
      rm -rf .bluemix
      
      # Generate Config Fetcher Script
      IFS='|' read -ra PROJECT_NAME <<< "$IDS_PROJECT_NAME"
      echo -e "${tools}${Yellow}    Generating config helper download script...${no_color}"
      echo -e "#!/bin/bash" > fetchConfig.sh
      echo -e "rm ./bluezone/configtweaks/settings.php" >> fetchConfig.sh
      echo -e "cf files${PROJECT_NAME[1]} /app/htdocs/drupal-7.41/sites/default/settings.php > ./bluezone/configtweaks/settings.php" >> fetchConfig.sh
      echo -e "sed -i -e '1,3d' ./bluezone/configtweaks/settings.php" >> fetchConfig.sh
      chmod +x fetchConfig.sh
      echo -e "${present} ${beers}${Green}  Way to go! Your Drupal Assembly present is ready!"
- name: SameDayDelivery
  inputs:
  - type: job
    stage: SelfAssembly
    job: WrapPresent
  triggers:
  - type: stage
  jobs:
  - name: OpenPresent
    type: deployer
    target:
      url: ${CF_TARGET_URL}
      organization: ${CF_ORGANIZATION}
      space: ${CF_SPACE}
      application: ${CF_APP}
    script: |
      #!/bin/bash
      # © Copyright IBM Corporation 2015.
      #
      # All rights reserved. This program and the accompanying materials
      # are made available under the terms of the Eclipse Public License v1.0
      # which accompanies this distribution, and is available at
      # http://www.eclipse.org/legal/epl-v10.html
      # For some reason, the deploy stage shell has tracing turned on.  Lets turn it off
      set +x
      ##########
      # Colors - Lets have some fun ##
      ##########
      Green='\e[0;32m'
      Red='\e[0;31m'
      Yellow='\e[0;33m'
      Cyan='\e[0;36m'
      no_color='\e[0m' # No Color
      beer='\xF0\x9f\x8d\xba'
      delivery='\xF0\x9F\x9A\x9A'
      beers='\xF0\x9F\x8D\xBB'
      eyes='\xF0\x9F\x91\x80'
      cloud='\xE2\x98\x81'
      litter='\xF0\x9F\x9A\xAE'
      fail='\xE2\x9B\x94'
      harpoons='\xE2\x87\x8C'
      tools='\xE2\x9A\x92'
      present='\xF0\x9F\x8E\x81'
      #############
      # http://serverfault.com/questions/7503/how-to-determine-if-a-bash-variable-is-empty#answer-382740
      if [ -z $(cf s|grep drupaldb|cut -d" " -f1-1) ]; then
        echo -e "${tools}${Yellow}  Pre-creating PostGresql Service named [${Cyan}drupaldb${Yellow}]${no_color}"
        q=0
        until [ $q -ge 5 ]
        do
           cf cs elephantsql lemur drupaldb > /dev/null 2>&1 && break
           q=$[$q+1]
           sleep 15
        done
      fi
      echo -e "${tools}${Yellow}  Sendgrid detection routine ...${no_color}" > /dev/null 2>&1
      if [ -n $(cf s|grep sendgrid|cut -d" " -f1-1) ] && [ $(cf s|grep sendgrid|cut -d" " -f1-1) != "sendmail" ]; then
        echo -e "${eyes}${Yellow}   Detected existing sendgrid service ${existingSendgrid} within target space${no_color}"
        echo -e "${tools}${Yellow}    Updating manifest.yml file to match target space sendgrid service${no_color}"
        sed -e "s/sendmail/$(cf s|grep sendgrid|cut -d" " -f1-1)/g" ./manifest.yml > manifest.new
        rm manifest.yml
        mv manifest.new manifest.yml
      else
        echo -e "${tools}${Yellow}    Pre-creating Sendgrid Service named [${Cyan}sendmail${Yellow}]${no_color}"
        t=0
        until [ $t -ge 5 ]
        do
           cf cs sendgrid free sendmail > /dev/null 2>&1 && break
           t=$[$t+1]
           sleep 15
        done
      fi

      p=0
      until [ $p -ge 2 ]
      do
         cf push "${CF_APP}" && echo -e "${beer} ${beers}${Green}  Congrats! Your secure Drupal deploy is up and running!${no_color}" && echo -e "${beer} ${beers}${Green}  finis coronat opus${no_color}" && break
         p=$[$p+1]
         sleep 10
      done
      # view logs
      #cf logs "${CF_APP}" --recent
